{% set version = "0.2.1" %}

package:
  name: r-grab
  version: {{ version }}

source:
  url: https://cran.r-project.org/src/contrib/GRAB_{{ version }}.tar.gz
  sha256: e5e5852fc003a96b7ece925fa5a4f82b1b8dbb54bfd730e832df147e90a88beb

build:
  number: 0
  rpaths:
    - lib/R/lib/                                      #[not win]
    - Library/lib/R/lib/                              #[win]

requirements:
  build:
    - {{ compiler('cxx') }}                           # [not win]
    - {{ stdlib("c") }}                               # [not win]
    - {{ compiler('m2w64_cxx') }}                     # [win]
    - {{ stdlib("m2w64_c") }}                         # [win]
    - m2-make                                         # [win]
    - m2-base                                         # [win]
    - m2-filesystem                                   # [win]
    - m2-sed                                          # [win]
  host:
    - r-base
    - r-rcpp
    - r-rcpparmadillo
    - r-rcppparallel
    - r-bh
    - zlib
    - libopenblas
    - r-dplyr
    - r-data.table
    - r-mvtnorm
    - r-matrix
    - r-rsqlite
    - r-lme4
    - r-ordinal
    - r-survival
    - r-igraph
    - r-dbplyr
    - r-optparse
    - r-tidyr
    - r-r.utils
    - r-skat
  run:
    - r-base
    - r-rcpp
    - r-rcpparmadillo
    - r-rcppparallel
    - r-bh
    - zlib
    - libopenblas
    - r-dplyr
    - r-data.table
    - r-mvtnorm
    - r-matrix
    - r-rsqlite
    - r-lme4
    - r-ordinal
    - r-survival
    - r-igraph
    - r-dbplyr
    - r-optparse
    - r-tidyr
    - r-r.utils
    - r-skat

test:
  commands:
    - $R -e "library('GRAB')"           # [not win]
    - "\"%R%\" -e \"library('GRAB')\""  # [win]

about:
  home: https://cran.r-project.org/package=GRAB
  license: GPL-2.0-or-later
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'
  summary: Genome-Wide Robust Analysis for Biobank Data (GRAB)
  description: Provides a comprehensive suite of genome-wide association study (GWAS) methods specifically designed for biobank-scale data. The package offers computationally efficient and robust association tests for time-to-event traits, ordinal categorical traits, and longitudinal traits. It also includes functions for simulating genotype and phenotype data to support research and method development.
  dev_url: https://github.com/GeneticAnalysisinBiobanks/GRAB

extra:
  recipe-maintainers:
    - WoodyMiao
